"""changed media table

Revision ID: 0ff2e9cb7920
Revises: 4c8deeb13f3c
Create Date: 2024-11-11 12:20:05.711219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff2e9cb7920'
down_revision = '4c8deeb13f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('media_video', sa.String(), nullable=True))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=5), nullable=False))
        batch_op.drop_column('media_video')
        batch_op.drop_column('media_image')

    # ### end Alembic commands ###
