<<<<<<<< HEAD:server/migrations/versions/4c8deeb13f3c_creates_tables.py
"""creates tables

Revision ID: 4c8deeb13f3c
Revises: 
Create Date: 2024-11-11 11:51:09.234790
========
"""creating models tables

Revision ID: 26b530bee1bd
Revises: 
Create Date: 2024-11-11 16:32:41.166539
>>>>>>>> 06b2a2ea34d98864fd34faa567c03697fd486e49:server/migrations/versions/26b530bee1bd_creating_models_tables.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:server/migrations/versions/4c8deeb13f3c_creates_tables.py
revision = '4c8deeb13f3c'
========
revision = '26b530bee1bd'
>>>>>>>> 06b2a2ea34d98864fd34faa567c03697fd486e49:server/migrations/versions/26b530bee1bd_creating_models_tables.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('under investigation', 'resolved', 'rejected'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('incident_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('under investigation', 'resolved', 'rejected'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins_acts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_report_id', sa.Integer(), nullable=True),
    sa.Column('emergency_only_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('status_change', 'flagged', 'resolved'), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emergency_only_id'], ['emergencies.id'], ),
    sa.ForeignKeyConstraint(['incident_report_id'], ['incident_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_medias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_report_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video'), nullable=False),
    sa.Column('media_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['incident_report_id'], ['incident_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_medias')
    op.drop_table('admins_acts')
    op.drop_table('incident_reports')
    op.drop_table('users')
    op.drop_table('notifications')
    op.drop_table('emergencies')
    # ### end Alembic commands ###
